/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
    File Name:	U1A4P1_Borg_Sleep
    Programmer:	Mathew Borg
    Date:	2021-02-17
    Description:This program calculates how long a person has been alive and 
    how mutch they should have slept.
 */
public class Calculator extends javax.swing.JFrame {
    public int BdayDayint, BdayMonthint, BdayYearint, DayDayint, DayMonthint, DayYearint; //Creats vareable interagers for our input values
    
    Calculations c = new Calculations(); //Allows us to use method and varables from our Calculations class
    
    /**
     * Creates new JFrame
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        BdayTitle = new javax.swing.JLabel();
        DayTitle = new javax.swing.JLabel();
        BdayDay = new javax.swing.JLabel();
        DayDay = new javax.swing.JLabel();
        TodayMonth = new javax.swing.JLabel();
        BdayMonth = new javax.swing.JLabel();
        BdayYear = new javax.swing.JLabel();
        TodayYear = new javax.swing.JLabel();
        BDayDayInput = new javax.swing.JTextField();
        BDayMonthInput = new javax.swing.JTextField();
        BDayYearInput = new javax.swing.JTextField();
        TodayDayInput = new javax.swing.JTextField();
        TodayMonthInput = new javax.swing.JTextField();
        TodayYearInput = new javax.swing.JTextField();
        Calculate = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        YouHaveBeenAliveFor = new javax.swing.JTextField();
        YouHaveSleptFor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 100, 200));
        Title.setText("Sleep Calculator");
        Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Author.setText("By: Mathew Borg");

        BdayTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BdayTitle.setText("Enter Your Birthdate");

        DayTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DayTitle.setText("Enter Today's Date");

        BdayDay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BdayDay.setText("Day");

        DayDay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DayDay.setText("Day");

        TodayMonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TodayMonth.setText("Month");

        BdayMonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BdayMonth.setText("Month");

        BdayYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BdayYear.setText("Year");

        TodayYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TodayYear.setText("Year");

        BDayDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDayDayInputActionPerformed(evt);
            }
        });

        BDayMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDayMonthInputActionPerformed(evt);
            }
        });

        BDayYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDayYearInputActionPerformed(evt);
            }
        });

        TodayDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodayDayInputActionPerformed(evt);
            }
        });

        TodayMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodayMonthInputActionPerformed(evt);
            }
        });

        TodayYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodayYearInputActionPerformed(evt);
            }
        });

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        YouHaveBeenAliveFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YouHaveBeenAliveForActionPerformed(evt);
            }
        });

        YouHaveSleptFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YouHaveSleptForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BdayMonth))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BdayDay))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BdayYear)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BDayYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDayDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TodayYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TodayDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DayDay, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TodayYear, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TodayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TodayMonth))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Exit)
                            .addComponent(Calculate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YouHaveSleptFor)
                            .addComponent(YouHaveBeenAliveFor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BdayTitle)
                        .addGap(95, 95, 95)
                        .addComponent(Author)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(DayTitle)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BdayTitle)
                            .addComponent(DayTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Author)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BdayDay)
                        .addComponent(BDayDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DayDay)
                        .addComponent(TodayDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TodayMonth)
                    .addComponent(BdayMonth)
                    .addComponent(BDayMonthInput)
                    .addComponent(TodayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BdayYear)
                    .addComponent(TodayYear)
                    .addComponent(BDayYearInput)
                    .addComponent(TodayYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calculate)
                    .addComponent(YouHaveBeenAliveFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(YouHaveSleptFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDayDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDayDayInputActionPerformed
        
    }//GEN-LAST:event_BDayDayInputActionPerformed

    private void BDayMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDayMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDayMonthInputActionPerformed

    private void BDayYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDayYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDayYearInputActionPerformed

    private void TodayMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodayMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodayMonthInputActionPerformed

    private void TodayDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodayDayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodayDayInputActionPerformed

    private void TodayYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodayYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodayYearInputActionPerformed

    private void YouHaveBeenAliveForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YouHaveBeenAliveForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YouHaveBeenAliveForActionPerformed

    private void YouHaveSleptForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YouHaveSleptForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YouHaveSleptForActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        String Bdayday, Bdaymonth, Bdayyear, Dayday, Daymonth, Dayyear, Alivefor, Sleptfor; //Creats a string for our input values 
        /**
         * Gets the text from our GUI input boxes and sets them to strings
         */
        Bdayday = BDayDayInput.getText();
        Bdaymonth = BDayMonthInput.getText();
        Bdayyear = BDayYearInput.getText();
        Dayday = TodayDayInput.getText();
        Daymonth = TodayMonthInput.getText();
        Dayyear = TodayYearInput.getText();
        
        /*
        * Passes the string data to the vareable ints we created
        */
        BdayDayint = Integer.parseInt(Bdayday);
        BdayMonthint = Integer.parseInt(Bdaymonth);
        BdayYearint = Integer.parseInt(Bdayyear);
        DayDayint = Integer.parseInt(Dayday);
        DayMonthint = Integer.parseInt(Daymonth);
        DayYearint = Integer.parseInt(Dayyear);
        
        //Passes the vareables to my calculator class
        c.timeCalculator(BdayDayint, BdayMonthint, BdayYearint, DayDayint, DayMonthint, DayYearint);
        
        //Passes the totaldays and totalsleep vars from my calculator class to my alivefor and sleptfor string
        Alivefor = Integer.toString(c.totaldays);
        Sleptfor = Integer.toString(c.totalsleep);
        
        //outputs the string value and some text to the GUI program 
        YouHaveBeenAliveFor.setText("You Have Been Alive For " + Alivefor + " Days");
        YouHaveSleptFor.setText("You Should Have Slept " + Sleptfor + " Hours");
        
    }//GEN-LAST:event_CalculateActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       System.exit(0); // closes the program when exit button pressed
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JTextField BDayDayInput;
    private javax.swing.JTextField BDayMonthInput;
    private javax.swing.JTextField BDayYearInput;
    private javax.swing.JLabel BdayDay;
    private javax.swing.JLabel BdayMonth;
    private javax.swing.JLabel BdayTitle;
    private javax.swing.JLabel BdayYear;
    private javax.swing.JButton Calculate;
    private javax.swing.JLabel DayDay;
    private javax.swing.JLabel DayTitle;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TodayDayInput;
    private javax.swing.JLabel TodayMonth;
    private javax.swing.JTextField TodayMonthInput;
    private javax.swing.JLabel TodayYear;
    private javax.swing.JTextField TodayYearInput;
    private javax.swing.JTextField YouHaveBeenAliveFor;
    private javax.swing.JTextField YouHaveSleptFor;
    // End of variables declaration//GEN-END:variables
}
