package u1a4p2_borg_quadroots;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
    File Name:	U1A4P1_Borg_QuadRoots
    Programmer:	Mathew Borg
    Date:	2021-02-19
    Description:This program calculates the  roots of a quadratic equation in the form ax2+bx+c = 0 
 */
public class Main extends javax.swing.JFrame {
   
    private int aInt, bInt, cInt; // Creats Ints for a,b,c inputs
    private String aString, bString, cString, x1, x2; // Creats Srings for input and final values
    
    private RootCalculations rC = new RootCalculations(); // Gives us access to the RootCalculations class
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        aRed = new javax.swing.JLabel();
        bGreen = new javax.swing.JLabel();
        cBlue = new javax.swing.JLabel();
        aInput = new javax.swing.JTextField();
        aRedTitle = new javax.swing.JLabel();
        x2Title = new javax.swing.JLabel();
        bGreenTitle = new javax.swing.JLabel();
        xTitle = new javax.swing.JLabel();
        cBlueTitle = new javax.swing.JLabel();
        zeroTitle = new javax.swing.JLabel();
        bInput = new javax.swing.JTextField();
        cInput = new javax.swing.JTextField();
        answerOutput = new javax.swing.JTextField();
        answerTitle = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 10, 10));
        Title.setText("Quad Roots");

        Author.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Author.setText("By: Mathew Borg");

        aRed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aRed.setForeground(new java.awt.Color(255, 0, 0));
        aRed.setText("a:");

        bGreen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bGreen.setForeground(new java.awt.Color(0, 255, 0));
        bGreen.setText("b:");

        cBlue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cBlue.setForeground(new java.awt.Color(0, 0, 255));
        cBlue.setText("c:");

        aInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aInputActionPerformed(evt);
            }
        });

        aRedTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aRedTitle.setForeground(new java.awt.Color(255, 0, 0));
        aRedTitle.setText("a");

        x2Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        x2Title.setText("x^2 +");

        bGreenTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bGreenTitle.setForeground(new java.awt.Color(0, 255, 0));
        bGreenTitle.setText("b");

        xTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        xTitle.setText("x +");

        cBlueTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cBlueTitle.setForeground(new java.awt.Color(0, 0, 255));
        cBlueTitle.setText("c");

        zeroTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zeroTitle.setText(" = 0");

        bInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInputActionPerformed(evt);
            }
        });

        cInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cInputActionPerformed(evt);
            }
        });

        answerOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerOutputActionPerformed(evt);
            }
        });

        answerTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerTitle.setText("Answer:");

        calculateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Title)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(Author)))
                            .addGap(133, 133, 133))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(answerOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aRed)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(aRedTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(x2Title))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cBlue)
                                    .addGap(2, 2, 2))
                                .addComponent(bGreen))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(answerTitle)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bGreenTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(xTitle)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cBlueTitle)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(zeroTitle))
                                        .addComponent(aInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(114, 114, 114)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calculateButton)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(2, 2, 2)
                .addComponent(Author)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aRed)
                            .addComponent(aInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aRedTitle)
                            .addComponent(x2Title)
                            .addComponent(bGreenTitle)
                            .addComponent(xTitle)
                            .addComponent(cBlueTitle)
                            .addComponent(zeroTitle))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGreen)
                    .addComponent(bInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBlue)
                    .addComponent(cInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Title.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aInputActionPerformed

    private void bInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bInputActionPerformed

    private void cInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cInputActionPerformed

    private void answerOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerOutputActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        /**
         * Gets the text from our GUI input boxes and sets them to strings
         */
        aString = aInput.getText();
        bString = bInput.getText();
        cString = cInput.getText();
        
        /*
        * Passes the string data to the vareable ints we created
        */
        try{ //trys to get number data 
            aInt = Integer.parseInt(aString);
            bInt = Integer.parseInt(bString);
            cInt = Integer.parseInt(cString);
        } catch (NumberFormatException e){ //if there are no numbers it will display Please Enter Numbers Only and retry the program
            answerOutput.setText("Please Enter Numbers Only");
            return;
        }
        rC.rootCalculations(aInt,bInt,cInt); //Passes the vareables to my rootCalculations method
        
        //Sets the x1 and x2 data from my RootCalculation class to strings
        x1 = Double.toString(rC.x1); 
        x2 = Double.toString(rC.x2);


        
        if (aInt == 0){ // if input a = 0 it will display Not A Quadratic Equation
            answerOutput.setText("Not A Quadratic Equation");
        }
        else if (rC.discriminant > 0){ // if the discriminant from the RootCalculations class is greater then 0 it will display the x1 and x2 roots
            answerOutput.setText("X = " + x1 + " X = " + x2);
        }
        else if (rC.discriminant < 0){ // if the discriminant from the RootCalculations class is less then 0 it will display Complex Roots
             answerOutput.setText("Complex Roots");
        } 


    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField aInput;
    private javax.swing.JLabel aRed;
    private javax.swing.JLabel aRedTitle;
    private javax.swing.JTextField answerOutput;
    private javax.swing.JLabel answerTitle;
    private javax.swing.JLabel bGreen;
    private javax.swing.JLabel bGreenTitle;
    private javax.swing.JTextField bInput;
    private javax.swing.JLabel cBlue;
    private javax.swing.JLabel cBlueTitle;
    private javax.swing.JTextField cInput;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel x2Title;
    private javax.swing.JLabel xTitle;
    private javax.swing.JLabel zeroTitle;
    // End of variables declaration//GEN-END:variables
}
