
import java.io.File;
import java.io.IOException;
import javax.swing.JTextArea;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mborg
 */
public class Main extends javax.swing.JFrame {
    private static final String xmlName = "courses.xml";
    private static final Document doc = findXml();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputXmlData = new javax.swing.JTextArea();
        btnAddData = new javax.swing.JButton();
        btnPrintXml = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 10, 10));
        title.setText("XML Create");

        author.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        author.setText("By: Mathew Borg");

        outputXmlData.setColumns(20);
        outputXmlData.setRows(5);
        jScrollPane1.setViewportView(outputXmlData);

        btnAddData.setText("Click To Add New Data");
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });

        btnPrintXml.setText("Click To Print XML");
        btnPrintXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintXmlActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(author)
                    .addComponent(title))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrintXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddData)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(author)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintXml)
                    .addComponent(btnAddData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintXmlActionPerformed
        printXML();
    }//GEN-LAST:event_btnPrintXmlActionPerformed

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataActionPerformed
        outputXmlData.setText("t");
        addXmlElement(0, "course", "schoolBoard", "RCDSB");
        addXmlElement(1, "course", "schoolBoard", "SCDSB");
        addXmlElement(2, "course", "schoolBoard", "SCDSB");
        
        updateXmlElement(0, "teacher", "Mr. Matthews");
        updateXmlElement(1, "teacher", "Mrs. Mitchell");
        updateXmlElement(2, "teacher", "Mr. Haas");
        
        updateXml();
        
        printXML();
    }//GEN-LAST:event_btnAddDataActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        removeXmlElement(0, "course", "schoolBoard");
        removeXmlElement(1, "course", "schoolBoard");
        removeXmlElement(2, "course", "schoolBoard");
        
        updateXmlElement(0, "teacher", "Teacher A");
        updateXmlElement(1, "teacher", "Teacher B");
        updateXmlElement(2, "teacher", "Teacher C");
        
        updateXml();
        
        printXML();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void printXML(){
        String[] code = printXml("course", "code", outputXmlData);
        String[] description = printXml("course", "description", outputXmlData);
        String[] teacher = printXml("course", "teacher", outputXmlData);
        String[] fileType = printXml("course", "fileType", outputXmlData);
        
        try{
        String[] schoolBoard = printXml("course", "schoolBoard", outputXmlData);
        outputXmlData.setText(code[0] + description[0] + teacher[0] + fileType[0] + schoolBoard[0] + "\n" + 
                              code[1] + description[1] + teacher[1] + fileType[1] + schoolBoard[1] + "\n" + 
                              code[2] + description[2] + teacher[2] + fileType[2] + schoolBoard[2] + "\n");
        }catch (Exception e){
            outputXmlData.setText(code[0] + description[0] + teacher[0] + fileType[0] + "\n" + 
                                  code[1] + description[1] + teacher[1] + fileType[1] + "\n" + 
                                  code[2] + description[2] + teacher[2] + fileType[2] + "\n");
        }
    }

    private static Document findXml() {
        
        try {
            DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
            Document doc = docBuilder.parse(xmlName);
            return doc;

        } catch (ParserConfigurationException pce) {
            pce.printStackTrace();
            return null;
        } catch (IOException ioe) {
            ioe.printStackTrace();
            return null;
        } catch (SAXException sae) {
            sae.printStackTrace();
            return null;
        }
    }
    
    private static void updateXml() {
        try {
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(new File(xmlName));
            transformer.transform(source, result);
        } catch (TransformerException tfe) {

        }
    }
    
    private static void addXmlElement(int position, String mainElement, String newElement, String newElementInfo){
        Node element = doc.getElementsByTagName(mainElement).item(position);
        Element addElement = doc.createElement(newElement);
        addElement.appendChild(doc.createTextNode(newElementInfo));
        element.appendChild(addElement);
    }
    
    private static void removeXmlElement(int position, String mainElement, String removeElement) {
        Element element = (Element) doc.getElementsByTagName(removeElement).item(position);
        element.getParentNode().removeChild(element);
        doc.normalize();
    }

    private static void updateXmlElement(int position, String elementName, String updatedElementInfo){
        Node element = doc.getElementsByTagName(elementName).item(position);
        element.setTextContent(updatedElementInfo);
        
    }

    private static String[] printXml(String elementName, String subElementName, JTextArea printArea) {
        NodeList listOfElements = doc.getElementsByTagName(elementName);
        String[] sTemp = new String[listOfElements.getLength()];
        
        for (int s = 0; s < listOfElements.getLength(); s++) {
            Node firstElementNode = listOfElements.item(s);
            
            
            Element theElement = (Element) firstElementNode;
            NodeList theElementList = theElement.getElementsByTagName(subElementName);
            Element theFirstElement = (Element) theElementList.item(0);
            NodeList textList = theFirstElement.getChildNodes();
            sTemp[s] = (((Node)textList.item(0)).getNodeValue().trim()+ "\n");
        }
        return sTemp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JButton btnAddData;
    private javax.swing.JButton btnPrintXml;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputXmlData;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
