import java.util.ArrayList;

/*
    programmer: Mathew Borg
    Date: 2021-04-5
    Program Name: U2A4P1_Borg_Student Marks
    Program Discription: This program is a Student Grades Application that 
                         simulates a grade book for a class with 15 or more 
                         students who each have four test scores.
*/
public class Main extends javax.swing.JFrame {
    String sFirstName, sLastName, sTestOne, sTestTwo, sTestThree, sTestFour; //creats strings
    Double testOne, testTwo, testThree, testFour; //creats doubles
    
    //creats 2d array list
    ArrayList<ArrayList<String>> studentNameData = new ArrayList(); 
    ArrayList<ArrayList<Double>> studentTestData = new ArrayList(); 
    //creats 2d array list to store all inputed data
    ArrayList<ArrayList<String>> allStudentInfo = new ArrayList(); 

    
    //creats arraylist
    ArrayList<String> studentName = new ArrayList();
    ArrayList<Double> studentTest = new ArrayList();
    //for printing all inputed values
    ArrayList<String> allStudents = new ArrayList();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitle = new javax.swing.JLabel();
        textAuthor = new javax.swing.JLabel();
        textFirstName = new javax.swing.JLabel();
        textLastName = new javax.swing.JLabel();
        textTest1 = new javax.swing.JLabel();
        textTest2 = new javax.swing.JLabel();
        textTest3 = new javax.swing.JLabel();
        textTest4 = new javax.swing.JLabel();
        inputFirstName = new javax.swing.JTextField();
        inputLastName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        inputTest1 = new javax.swing.JTextField();
        inputTest2 = new javax.swing.JTextField();
        inputTest3 = new javax.swing.JTextField();
        inputTest4 = new javax.swing.JTextField();
        btnStudentAvarage = new javax.swing.JButton();
        btnCourseAverage = new javax.swing.JButton();
        outputAverage = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textTitle.setForeground(new java.awt.Color(10, 255, 10));
        textTitle.setText("Student Marks");

        textAuthor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAuthor.setText("By: Mathew Borg");

        textFirstName.setText("First Name:");

        textLastName.setText("Last Name:");

        textTest1.setText("(%) Test 1:");

        textTest2.setText("(%) Test 2:");

        textTest3.setText("(%) Test 3:");

        textTest4.setText("(%) Test 4:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        inputTest1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputTest2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputTest3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputTest4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnStudentAvarage.setText("Student Average");
        btnStudentAvarage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAvarageActionPerformed(evt);
            }
        });

        btnCourseAverage.setText("Course Average");
        btnCourseAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAverageActionPerformed(evt);
            }
        });

        outputAverage.setEditable(false);
        outputAverage.setColumns(20);
        outputAverage.setRows(5);

        outputList.setEditable(false);
        outputList.setColumns(20);
        outputList.setRows(5);
        outputList.setOpaque(false);
        jScrollPane1.setViewportView(outputList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textTest1)
                                    .addComponent(textLastName)
                                    .addComponent(textTest2)
                                    .addComponent(textTest3)
                                    .addComponent(textTest4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputFirstName)
                                    .addComponent(inputLastName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputTest4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(inputTest2)
                                            .addComponent(inputTest1)
                                            .addComponent(inputTest3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnStudentAvarage, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(btnCourseAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(outputAverage)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTitle)
                                .addGap(0, 58, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(textAuthor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFirstName)
                    .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLastName)
                    .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTest1)
                    .addComponent(btnAdd)
                    .addComponent(inputTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentAvarage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTest2)
                    .addComponent(btnList)
                    .addComponent(inputTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseAverage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTest3)
                    .addComponent(inputTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTest4)
                    .addComponent(btnExit)
                    .addComponent(inputTest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        outputAverage.getAccessibleContext().setAccessibleParent(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //gets text input and stores them all in strings
        sFirstName = inputFirstName.getText(); 
        sLastName = inputLastName.getText();
        sTestOne = inputTest1.getText();
        sTestTwo = inputTest2.getText();
        sTestThree = inputTest3.getText();
        sTestFour = inputTest4.getText();              
        
        try{ //trys to convert strings to double
            testOne = Double.parseDouble(sTestOne);
            testTwo = Double.parseDouble(sTestTwo);
            testThree = Double.parseDouble(sTestThree);
            testFour = Double.parseDouble(sTestFour);
        }catch(NumberFormatException e){ //if there are no numbers it will display Enter Numbers Only and retry the program
            outputAverage.setText("Enter Numbers Only");
            return;
        }
        
        //Adds sStrings to ArrayLists
        studentName.add(sFirstName);
        studentName.add(sLastName);
        studentTest.add(testOne);
        studentTest.add(testTwo);
        studentTest.add(testThree);
        studentTest.add(testFour);
        
        //Adds sStrings to all value ArrayLists
        allStudents.add(sFirstName);
        allStudents.add(sLastName);
        allStudents.add(sTestOne);
        allStudents.add(sTestTwo);
        allStudents.add(sTestThree);
        allStudents.add(sTestFour);
        
        //Adds ArrayLists to 2d ArrayLists
        studentNameData.add(new ArrayList<>(studentName));
        studentTestData.add(new ArrayList<>(studentTest));   
        allStudentInfo.add(new ArrayList<>(allStudents));
        
        //clears ArrayList 
        studentName.clear();
        studentTest.clear();
        allStudents.clear();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        String result = ""; //creats String
        //initalises arraylist with 2 for loops
        for (int i = 0; i < allStudentInfo.size(); i++) {
            for (int j = 0; j < allStudentInfo.get(i).size(); j++) {
                result += allStudentInfo.get(i).get(j) + " ";// adds allStudentInfo to result with and adds a space
            }
            result += "\n"; //adds a new line
        }
        outputList.setText("First Name: Last Name: Test1: Test2: Test3: Test4:" + "\n" + result); //prints "First Name: Last Name: Test1: Test2: Test3: Test4:" + "\n" + result to outputList
    }//GEN-LAST:event_btnListActionPerformed
    
    private void btnStudentAvarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAvarageActionPerformed
        //gets text from name feilds 
        sFirstName = inputFirstName.getText(); 
        sLastName = inputLastName.getText();
        
        double studentAverage = MarkCalculator.studentAverage(studentTestData, studentNameData, sFirstName, sLastName); //sends arrays and strings to method and stores method return value in studentAverage double 
        
        studentAverage = Math.round(studentAverage * 100.0) / 100.0; //rounds stundet average to 2 decimal places
        
        String sStudentAverage = Double.toString(studentAverage); //converts double to string
        outputAverage.setText(sFirstName + " " +sLastName + "'s average is " + sStudentAverage +" %"); //sets outputAverage Text
    }//GEN-LAST:event_btnStudentAvarageActionPerformed

    private void btnCourseAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAverageActionPerformed
        double courseAverage = MarkCalculator.courseAverage(studentTestData); //sends arrays and strings to method and stores method return value in courseAverage double 
        courseAverage = Math.round(courseAverage * 100.0) / 100.0; //Rounds course average to 2 decimal places 
        
        String sCourseAverage = Double.toString(courseAverage); //converts double to string
        outputAverage.setText("Course average is " + sCourseAverage +" %"); //sets outputAverage Text
    }//GEN-LAST:event_btnCourseAverageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); // exits program
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCourseAverage;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnStudentAvarage;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JTextField inputTest1;
    private javax.swing.JTextField inputTest2;
    private javax.swing.JTextField inputTest3;
    private javax.swing.JTextField inputTest4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputAverage;
    private javax.swing.JTextArea outputList;
    private javax.swing.JLabel textAuthor;
    private javax.swing.JLabel textFirstName;
    private javax.swing.JLabel textLastName;
    private javax.swing.JLabel textTest1;
    private javax.swing.JLabel textTest2;
    private javax.swing.JLabel textTest3;
    private javax.swing.JLabel textTest4;
    private javax.swing.JLabel textTitle;
    // End of variables declaration//GEN-END:variables
}
